// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameStudent = "students"

// Student mapped from table <students>
type Student struct {
	ID            int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string     `gorm:"column:name;not null;comment:学生姓名" json:"name"`                              // 学生姓名
	IDCard        string     `gorm:"column:id_card;not null;comment:身份证号" json:"id_card"`                        // 身份证号
	AdmissionDate time.Time  `gorm:"column:admission_date;not null;comment:入学日期" json:"admission_date"`          // 入学日期
	ClassID       *int32     `gorm:"column:class_id;comment:所属班级" json:"class_id"`                               // 所属班级
	Birthdate     time.Time  `gorm:"column:birthdate;not null;comment:生日" json:"birthdate"`                      // 生日
	ParentName    string     `gorm:"column:parent_name;not null;comment:家长姓名" json:"parent_name"`                // 家长姓名
	ParentPhone   string     `gorm:"column:parent_phone;not null;comment:家长联系电话" json:"parent_phone"`            // 家长联系电话
	CreatedAt     *time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	IsDel         *int32     `gorm:"column:is_del;comment:是否删除（0: 未删除, 1: 已删除）" json:"is_del"`                   // 是否删除（0: 未删除, 1: 已删除）
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
